"""initial schema

Revision ID: 0757229302c7
Revises: 
Create Date: 2026-01-11 12:54:48.073364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0757229302c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('hashed_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key_id'),
    sa.UniqueConstraint('hashed_key')
    )
    op.create_index('ix_api_keys_hashed_key', 'api_keys', ['hashed_key'], unique=False)
    op.create_table('categories',
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('category')
    )
    op.create_table('offers',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('mpn', sa.String(length=255), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('project_id', 'mpn')
    )
    op.create_index('ix_offers_expires_at', 'offers', ['expires_at'], unique=False)
    op.create_table('parts',
    sa.Column('mpn', sa.String(length=255), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('api_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('mpn')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index('ix_projects_created_at', 'projects', ['created_at'], unique=False)
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.String(length=255), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_table('update_log',
    sa.Column('update_id', sa.String(length=64), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('update_id')
    )
    op.create_index('ix_update_log_timestamp', 'update_log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_update_log_timestamp', table_name='update_log')
    op.drop_table('update_log')
    op.drop_table('suppliers')
    op.drop_index('ix_projects_created_at', table_name='projects')
    op.drop_table('projects')
    op.drop_table('parts')
    op.drop_index('ix_offers_expires_at', table_name='offers')
    op.drop_table('offers')
    op.drop_table('categories')
    op.drop_index('ix_api_keys_hashed_key', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
